### ISSUE TITLE
Do release for 2.4.0 and 3.0.0

### ISSUE THREAD

**Issue by jcurl** [jcurl/RJCP.DLL.SerialPortStream#130]
Prepare and perform the release for the NuGet packages for the newer RJCP.SerialPortStream deliveries. For 3.0.0, this will require a bunch of new Nuget packages also.

**Comment by davehutchy** [comment]
Hey, 

Would it be possible to get 2.4.0 released for NuGet or get this [commit](https://github.com/jcurl/RJCP.DLL.SerialPortStream/commit/c3baf2690bb3102fbb15525ea8746a66b43e58e3) released as 2.3.2 for NuGet. We are experiencing the bug mentioned in the commit.

Thanks

**Comment by jcurl** [comment]
Did release 2.4.0. Not prepared for release 3.0.0 yet, which is a change to the project structure.
