### ISSUE TITLE
Can't compile - missing source code

### ISSUE THREAD

**Issue by hallsbyra** [jcurl/RJCP.DLL.SerialPortStream#134]
Where can I find these projects, referenced by SerialPortStream.csproj, but not included in this repo:

```
  <ItemGroup>
    <ProjectReference Include="..\..\bufferio\BufferIO\RJCP.IO.Buffer.csproj" />
    <ProjectReference Include="..\..\trace\Trace\RJCP.Diagnostics.Trace.csproj" />
  </ItemGroup>
```

**Comment by hallsbyra** [comment]
Ok, just found'em! :)

* https://github.com/jcurl/RJCP.DLL.BufferIO
* https://github.com/jcurl/RJCP.DLL.Trace

**Comment by jcurl** [comment]
The idea is to check out https://github.com/jcurl/RJCP.base and do a submodule init. Then you can be sure that the interfaces between the repositories are compatible. It also of course sets up the folder structure. Building can still be done in the repo directly with `dotnet build`.

You could also check out the `v2.x` branch which doesn't have these dependencies.
