### ISSUE TITLE
can not find Projects: RJCP.Diagnostics.Trace  RJCP.IO.DeviceMgr

### ISSUE THREAD

**Issue by yangjieshao** [jcurl/RJCP.DLL.SerialPortStream#141]
```
  <ItemGroup>
    <ProjectReference Include="..\..\bufferio\BufferIO\RJCP.IO.Buffer.csproj" />
    <ProjectReference Include="..\..\trace\Trace\RJCP.Diagnostics.Trace.csproj" />
    <ProjectReference Include="..\..\devicemgr\DeviceMgr\RJCP.IO.DeviceMgr.csproj" />
  </ItemGroup>
```

can not find `RJCP.Diagnostics.Trace` and `RJCP.IO.DeviceMgr`

**Comment by jcurl** [comment]
I'm glad you found the answer. Check out my `RJCP.base` repository. Add the path `configmgr` to your path and run `git rj init`, which gets the HEAD of all repositories.

Then you can build the SerialPortStream using `dotnet build`.
