### ISSUE TITLE
Multiple dependencies missing from the project.

### ISSUE THREAD

**Issue by Sebbasstt** [jcurl/RJCP.DLL.SerialPortStream#147]
Unable to compile this project. Is it possible to obtain the component only without racking my brains to find everything that is missing to compile it?

RJCP.IO.Buffer
RJCP.IO.DeviceMgr

I'm not very advanced in .net core and it seems to be very complicated to compile to get the .dll that I need.

I name only these two but, there are more than 100 errors if I want to compile it. 

I'm looking for something simple to use a serial port in .net framework 4.8 under mono so I don't want to bother with an incomplete project

thank you

**Comment by jcurl** [comment]
You can do this in two ways:

1. Check out my other repositories at the same level as this repo, so it looks like:
  * `serialportstream` -> rjcp.dll.serialportstream.git
  * `environment` -> RJCP.DLL.Environment.git
  * `bufferio` -> RJCP.DLL.BufferIO.git
  * `trace` -> RJCP.DLL.Trace.git
  * `devicemgr` -> RJCP.DLL.DeviceMgr.git
2. The second way, is to check out my base repository, initialise and build from there
  - git checkout rjcp.base
  - git submodule init
  - cd framework/serialportstream
  - dotnet build
