### ISSUE TITLE
Do I still need to compile libnserial.so if using .net framework on linux?

### ISSUE THREAD

**Issue by rathbone01** [jcurl/RJCP.DLL.SerialPortStream#150]
In the documentation it appears that you need to compile libnserial.so if using linux, is that only for mono, or also for a .net framework build with a linux target?

If it is still needed is there documentation somewhere on how to do that?

Thanks!

**Comment by jcurl** [comment]
You will need to compile `libnserial.so` for .NET Mono and .NET Core. If you're using Debian / Ubuntu, you can install the debian files attached with the releases. If you'd like to build it yourself, see the documentation at [BUILD.md](https://github.com/jcurl/RJCP.DLL.SerialPortStream/blob/master/dll/serialunix/BUILD.md). There are other `README` files providing additional information.

It uses `cmake`, so follow the usual rules for building for your platform.

**Comment by rathbone01** [comment]
Alright, thank you for your help!
