### ISSUE TITLE
COM Port with FILE_TYPE_DISK throwing exception

### ISSUE THREAD

**Issue by ekarcnevets** [jcurl/RJCP.DLL.SerialPortStream#64]
Hi, I have recently tried to use your library with a usb-serial converter I've got. I was getting an error when calling Open() 'Wrong file type: COM10'. This comes from [here](https://github.com/jcurl/SerialPortStream/blob/dbca7120ef8c1903fbb8d36a489113c1f1bcfb0a/code/Native/WinNativeSerial.cs#L849).

There is no problem reading the COM port in Putty, so I tried building the dll myself, with the check commented out and the data comes through fine in the library.

Is the file type being disk unusual, and just a quirk of this device?

Thanks.

**Comment by jcurl** [comment]
Thanks for the report. Can you please tell me the device?

When you break point, what is the value of 't'?

**Comment by ekarcnevets** [comment]
I understand it's a little strange. The device is https://www.u-blox.com/en/product/neo-m8u-module. UBlox supplies a 'virtual com port' driver for it.

Yes, it shows up when using the GetPortNames API.

**Comment by jcurl** [comment]
I've created a small patch. Can you please test the branch "feature/issue-64" that it solves your problem? If so, then I'll push it to the v2.x branch and prepare it for the next release.
