### ISSUE TITLE
cmake error (cmake version 2.8.12.2) latest commit needs > 2.8.12.2

### ISSUE THREAD

**Issue by benmutlu** [jcurl/RJCP.DLL.SerialPortStream#81]
when trying to make latest commit gives cmake error "cmake error (cmake version 2.8.12.2)" 

for install > 2.8.12 , follow;

sudo yum remove cmake -y
wget https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz
tar -zxvf cmake-3.6.2.tar.gz
cd cmake-3.6.2
sudo ./bootstrap --prefix=/usr/local
sudo make
sudo make install
echo "PATH=/usr/local/bin:\$PATH:\$HOME/bin" >> ~/.bash_profile

**Comment by jcurl** [comment]
What distribution are you building with?

**Comment by benmutlu** [comment]
centos7 - 3.10.0-957.1.3.el7.x86_64

**Comment by jcurl** [comment]
Closing as I don't have time to investigate this.
